language: node_js
node_js:
- 8.14.0
install: 
  - npm install
script: gatsby build
branches:
  only:
      - master
env:
  global:
  - 'SFTP_USER=popflyxp'
  - 'SFTP_PASSWORD=$SFTP_PASSWORD'
after_success:
- curl --ftp-create-dirs
       -T filename
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@charlton.dreamhost.com/home/popflyxp/popflyxp.com