env:
  global:
  - 'SFTP_USER=popflyxp'
  - 'SFTP_PASSWORD=$SFTP_PASSWORD'
after_success:
- curl --ftp-create-dirs
       -T filename
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@charlton.dreamhost.com/home/popflyxp/popflyxp.com