language: node_js
node_js:
- 10.13.0
install: 
  - npm install
script: gatsby build
branches:
  only:
      - master
env:
  global:
  - 'SFTP_USER=popflyxp'
  - 'SFTP_PASSWORD=$SFTP_PASSWORD'
  - 'SFTP_KEY=bTlMUjJqTG9VUElDeGxpWUx5SFV5QWRNSkFUYjh4MGJ0Z2lHQm9kNHNwNA=='
after_success:
- echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
- sftp --key /tmp/sftp_rsa popflyxp@charlton.dreamhost.com:popflyxp.com/ <<< $'put -r ./public/*'