language: node_js
node_js:
- 10.13.0
install: 
  - npm install
script: gatsby build
branches:
  only:
      - master
env:
  global:
  - 'SFTP_USER=popflyxp'
  - 'SFTP_PASSWORD=$SFTP_PASSWORD'
after_success:
- find public -type f -exec curl --ftp-create-dirs -T {} sftp://${SFTP_USER}:${SFTP_PASSWORD}@charlton.dreamhost.com//home/popflyxp/popflyxp.com/{}